version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: uasa-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: investoreduuasa
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
