services:
  # Type of service
  - type: web
    name: uasa-backend
    env: node
    plan: free
    healthCheckPath: /api/health
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
