-- Create Publications Table
CREATE TABLE IF NOT EXISTS publications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    authority_name VARCHAR(255) NOT NULL,
    category ENUM('Brochure', 'Code', 'General', 'Guide', 'Others', 'Report', 'Study') NOT NULL,
    file_url VARCHAR(1000),
    date_published DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_authority (authority_name),
    INDEX idx_category (category),
    INDEX idx_active (is_active),
    INDEX idx_date_published (date_published)
);

DELETE FROM publications;

INSERT INTO publications (title, description, authority_name, category, file_url) VALUES
('General Guidelines', NULL, 'Jordan Securities Commission', 'General', 'http://www.jsc.gov.jo/page/investor_culture.aspx'),
('Investor Education and Training Events', NULL, 'Jordan Securities Commission', 'General', 'http://pdf.usaid.gov/pdf_docs/Pnacy596.pdf'),
('Investor Education and Training Events Assistance', NULL, 'Jordan Securities Commission', 'Study', 'http://pdf.usaid.gov/pdf_docs/Pnacy596.pdf'),
('Publications', NULL, 'Jordan Securities Commission', 'Guide', 'http://www.jsc.gov.jo/page/publications.aspx'),
('Awareness messages', NULL, 'Jordan Securities Commission', 'Others', 'http://www.jsc.gov.jo/page/awareness_messages.aspx'),
('Quiz', NULL, 'Commission d''Organisation et de Surveillance des opérations de Bourse', 'Others', 'http://www.cosob.org/quiz/'),
('Videos', NULL, 'Commission d''Organisation et de Surveillance des opérations de Bourse', 'Others', 'http://www.cosob.org/videos/'),
('Games', NULL, 'Commission d''Organisation et de Surveillance des opérations de Bourse', 'Others', 'http://www.cosob.org/jeux/'),
('Financial Glossary', NULL, 'Commission d''Organisation et de Surveillance des opérations de Bourse', 'Others', 'http://www.cosob.org/lexique/'),
('Investor Guides', '(French Only)', 'Commission d''Organisation et de Surveillance des opérations de Bourse', 'Guide', 'http://www.cosob.org/guides/'),
('Capital Market Investment Basics', NULL, 'Saudi Capital Market Authority', 'General', 'https://cma.org.sa/en/Awareness/InvestmentBasics/Pages/default.aspx'),
('Capital Market', NULL, 'Saudi Capital Market Authority', 'General', 'https://cma.org.sa/en/Awareness/Pages/CapitalMarket.aspx'),
('Investment Funds', NULL, 'Saudi Capital Market Authority', 'General', 'https://cma.org.sa/en/Awareness/IFs/Pages/default.aspx'),
('Investment Portfolio Management', NULL, 'Saudi Capital Market Authority', 'General', 'https://cma.org.sa/en/Awareness/Pages/IFManagement.aspx'),
('Information Sources', NULL, 'Saudi Capital Market Authority', 'General', 'https://cma.org.sa/en/Awareness/InformationSources/Pages/default.aspx'),
('The Financial Ratio', NULL, 'Saudi Capital Market Authority', 'General', 'https://cma.org.sa/en/Awareness/Pages/financialRatios.aspx'),
('Investor Awareness Guidebooks', NULL, 'Saudi Capital Market Authority', 'Guide', 'https://cma.org.sa/en/Awareness/Publications/Pages/booklets.aspx'),
('Glossary', NULL, 'Saudi Capital Market Authority', 'Others', 'https://cma.org.sa/en/Awareness/Pages/Glossary.aspx'),
('Investor Awareness Infographics', NULL, 'Saudi Capital Market Authority', 'Others', 'https://cma.org.sa/en/Awareness/Publications/Pages/infographics.aspx'),
('General publications', NULL, 'Syrian Commission on financial markets and securities', 'General', 'http://scfms.sy/awarenessLetters/ar/37/0/نشرات-التوعية'),
('International Organizations Reports', NULL, 'Syrian Commission on financial markets and securities', 'Report', 'http://scfms.sy/page/ar/1854/0/تقارير-المنظمات-الدولية'),
('Researches', NULL, 'Syrian Commission on financial markets and securities', 'Study', 'http://scfms.sy/StudiesResarch/ar/2205/0/دراسات-وأبحاث'),
('Terms', NULL, 'Syrian Commission on financial markets and securities', 'Others', 'http://scfms.sy/page/ar/516/0/مصطلحات'),
('Quiz', NULL, 'Syrian Commission on financial markets and securities', 'Others', 'http://scfms.sy/quiz/ar/41/0/اختبر-معلوماتك'),
('Researches and Studies', NULL, 'Palestine Capital Market Authority', 'Report', 'http://www.pcma.ps/portal/awareness/SitePages/researchesAndStudiesAuth.aspx'),
('Awareness messages', NULL, 'Palestine Capital Market Authority', 'Guide', 'http://www.pcma.ps/portal/awareness/Pages/Awarness_msgs.aspx'),
('seminars & Conferences', NULL, 'Palestine Capital Market Authority', 'Others', 'http://www.pcma.ps/portal/awareness/SitePages/seminarsConferancesAuth.aspx'),
('Investor Corner', NULL, 'Qatar Financial Markets Authority', 'General', 'https://www.qe.com.qa/ar/investor-corner'),
('QE Publications', NULL, 'Qatar Financial Markets Authority', 'General', 'https://www.qe.com.qa/ar/qe-publications'),
('Investor Awareness', NULL, 'Qatar Financial Markets Authority', 'Brochure', 'https://www.qfma.org.qa/Arabic/MediaCenter/Pages/InvestorAwareness.aspx'),
('Awareness', NULL, 'Kuwait Capital Markets Authority', 'General', 'https://www.cma.gov.kw/ar/web/cma/awareness'),
('Investor Education', NULL, 'Capital Markets Authority of Lebanon', 'General', 'https://www.cma.gov.lb/investor-education/'),
('Index', NULL, 'Financial Regulatory Authority - Egypt', 'General', 'http://www.iinvest.gov.eg/general/index.jsp'),
('Reports', NULL, 'Financial Regulatory Authority - Egypt', 'Report', 'http://www.fra.gov.eg/content/efsa_ar/efsa_pages/reports_printing.htm'),
('Investor Awareness', NULL, 'Autorité Marocaine du Marché des Capitaux (AMMC)', 'General', 'http://www.ammc.ma/en/espace-epargnants'),
('Investor Protection', NULL, 'Conseil du Marché Financier - Tunisia', 'General', 'http://www.bvmt.com.tn/fr/content/protection-de-linvestisseur'),
('Investor Guide', NULL, 'Conseil du Marché Financier - Tunisia', 'Guide', 'http://www.bvmt.com.tn/sites/default/files/articles/guide-de-linvestisseur_1.pdf'),
('Financial products Guide', NULL, 'Conseil du Marché Financier - Tunisia', 'Guide', 'http://www.bvmt.com.tn/sites/default/files/articles/guide-des-produits-boursiers.pdf'),
('Investor Protection', NULL, 'Conseil du Marché Financier - Tunisia', 'Guide', 'http://www.bvmt.com.tn/fr/content/protection-de-linvestisseur');
