-- Insert IOSCO Framework data
INSERT INTO frameworks (
  title, 
  description, 
  author, 
  date, 
  file_url, 
  content, 
  authority_id, 
  category_id, 
  views, 
  downloads, 
  is_active
) VALUES (
  'IOSCO Framework',
  'The need for investor education and financial literacy has never been greater. As the financial marketplace continues to evolve and innovate, investment products are becoming increasingly complex and financial services increasingly diverse. Greater understanding of key financial concepts is required on the part of retail investors to understand and evaluate the choices available to them and avoid fraud. Underscoring the importance of investor education and financial literacy is the critical – and increasing – need for retirement planning as responsibility for saving and investing in many jurisdictions shifts from the employer to the individual.\n\nThe International Organization of Securities Commissions (IOSCO) is responding to these challenges. The IOSCO Board approved the establishment of the Committee on Retail Investors (C8). The committee\'s primary mandate is to conduct IOSCO\'s policy work on retail investor education and financial literacy. Its secondary mandate is to advise the IOSCO Board on emerging retail investor protection matters and conduct investor protection policy work as directed by the IOSCO Board.\n\nThe following framework identifies practices currently used by C8 members to help guide IOSCO members in developing and enhancing their own investor education and financial literacy programs:\n\nPractice 1:\nFocus investor education and financial literacy programs on improving retail investor knowledge of basic core competencies for investing, and on raising awareness, and promoting understanding of the types of investment products and services that are available.\n\nPractice 2:\nDevelop investor education and financial literacy programs that meet investor needs and support regulatory initiatives.\n\nPractice 3:\nDevelop investor education and financial literacy programs to meet the needs of specific audiences.\n\nPractice 4:\nConsider insights gathered from research when developing investor education and financial literacy programs.\n\nPractice 5:\nDevelop investor education and financial literacy programs with clear and measurable outcomes, and where possible, evaluate them on an ongoing basis.\n\nPractice 6:\nCollaborate or partner with other relevant organisations in developing and delivering investor education and financial literacy programs.\n\nPractice 7:\nWhen developing investor education and financial literacy programs, consider national strategies and/or collaboration with other organisations to complement or reinforce financial education and financial consumer protection programs generally.\n\nPractice 8:\nPromote international cooperation, sharing of information and coordination on investor education and financial literacy, including forums for exchange of information and experiences within IOSCO and with other agencies and organisations.\n\n***See more at: IOSCO Strategic Framework for Investor Education and Financial Literacy.',
  'International Organization of Securities Commissions (IOSCO)',
  '2024-01-15',
  'http://www.iosco.org/library/pubdocs/pdf/IOSCOPD462.pdf',
  'The need for investor education and financial literacy has never been greater. As the financial marketplace continues to evolve and innovate, investment products are becoming increasingly complex and financial services increasingly diverse. Greater understanding of key financial concepts is required on the part of retail investors to understand and evaluate the choices available to them and avoid fraud. Underscoring the importance of investor education and financial literacy is the critical – and increasing – need for retirement planning as responsibility for saving and investing in many jurisdictions shifts from the employer to the individual.\n\nThe International Organization of Securities Commissions (IOSCO) is responding to these challenges. The IOSCO Board approved the establishment of the Committee on Retail Investors (C8). The committee\'s primary mandate is to conduct IOSCO\'s policy work on retail investor education and financial literacy. Its secondary mandate is to advise the IOSCO Board on emerging retail investor protection matters and conduct investor protection policy work as directed by the IOSCO Board.\n\nThe following framework identifies practices currently used by C8 members to help guide IOSCO members in developing and enhancing their own investor education and financial literacy programs:\n\nPractice 1:\nFocus investor education and financial literacy programs on improving retail investor knowledge of basic core competencies for investing, and on raising awareness, and promoting understanding of the types of investment products and services that are available.\n\nPractice 2:\nDevelop investor education and financial literacy programs that meet investor needs and support regulatory initiatives.\n\nPractice 3:\nDevelop investor education and financial literacy programs to meet the needs of specific audiences.\n\nPractice 4:\nConsider insights gathered from research when developing investor education and financial literacy programs.\n\nPractice 5:\nDevelop investor education and financial literacy programs with clear and measurable outcomes, and where possible, evaluate them on an ongoing basis.\n\nPractice 6:\nCollaborate or partner with other relevant organisations in developing and delivering investor education and financial literacy programs.\n\nPractice 7:\nWhen developing investor education and financial literacy programs, consider national strategies and/or collaboration with other organisations to complement or reinforce financial education and financial consumer protection programs generally.\n\nPractice 8:\nPromote international cooperation, sharing of information and coordination on investor education and financial literacy, including forums for exchange of information and experiences within IOSCO and with other agencies and organisations.\n\n***See more at: IOSCO Strategic Framework for Investor Education and Financial Literacy.',
  NULL,
  NULL,
  0,
  0,
  TRUE
);
